### ISSUE TITLE
How do I break `forEachPipeline` execution on condition? W/o throwing error for that

### ISSUE THREAD

**Issue by wzup** [joyent/node-vasync#34]
Your tutorial says
> forEachPipeline: invoke the same function on N inputs in series **(and stop on failure)**

So, to stop execution, I have to simulate a failure, right? But can I stop execution w/o simulating a failure? Just by using `if/else`? Like this:
```
if(true) {
    exit_loop_go_to_last_cb(null, result);
}
```

Now I have generate an error to exit execution. I don't like it. Because actually I don't have errors happen. I have a condition happen that is not an error. So it is illogical to do this way:
```
if(true) {
    callback(new Error('My condition is true'), result)
}
```

**Comment by davepacheco** [comment]
That's a common use-case.  I'd suggest checking out `barrier` instead of the pipeline functions.  That would allow you to decide upon completion of each asynchronous step exactly which other asynchronous steps you want to wait for.
