### ISSUE TITLE
want race

### ISSUE THREAD

**Issue by jlevon** [joyent/node-vasync#39]
It would be useful if we had an equivalent to `async.race()`.

**Comment by davepacheco** [comment]
It seems a little unsafe that this mechanism leaves unspecified what happens to the outstanding asynchronous operations when this operation completes.  It seems like this could really easily lead to resource leakage or subtle bugs.  Are there compelling use-cases for it?

**Comment by jlevon** [comment]
I didn't mean to leave it unspecified, but perhaps the docs I added aren't clear that all ops continue running unless explicitly cleaned up in the callback (I can't think of any way this couldn't be true?).

If there's some other pattern I'm not aware of that does something similar to `async.race()` I'm all ears.
My specific case is timing out a 'pwait' on a process that might run forever.

**Comment by jclulow** [comment]
For that particular case, you could use the `forkexec` library to run `pwait` with a timeout; e.g.,

```javascript
var mod_verror = require('verror');
var mod_forkexec = require('forkexec');

var VE = mod_verror.VError;

function
pwait(pid, delay_ms, callback)
{
        mod_forkexec.forkExecWait({ argv: [ '/usr/bin/pwait', '' + pid ],
            timeout: delay_ms }, function (err, info) {
                if (err) {
                        callback(new VE(err, 'pwait(%d) failed', pid));
                        return;
                }

                callback();
        });
}
```

More generally, I'd be inclined to do something like this:

```javascript
var mod_verror = require('verror');
var mod_child = require('child_process');

var VE = mod_verror.VError;

function
pwait(pid, delay_ms, callback)
{
        var proc;

        var too_long = false;
        var timeo = setTimeout(function () {
                too_long = true;
                proc.kill('SIGKILL');
        }, delay_ms);

        proc = mod_child.execFile('/usr/bin/pwait', [ '' + pid ],
            function (err, stdout, stderr) {
                clearTimeout(timeo);

                if (too_long) {
                        callback(new VE(err, 'pwait(%d) timed out', pid));
                        return;
                }

                if (err) {
                        callback(new VE(err, 'pwait(%d) failed', pid));
                        return;
                }

                callback();
        });
}
```

This has the advantage of not returning control to `callback()` without explicitly cleaning up all resources.

**Comment by jlevon** [comment]
@davepacheco: I knew about that, but it's not suitable in context, as it doesn't let you differentiate simply between timeout or other SIGKILL.

@jclulow thanks, I'll use forkExecWait. Your second variant also seems fine in this case, as long as nobody ever tries to callback from the timeout case itself for any reason (the problem with the current code).
